CUDA_VISIBLE_DEVICES: '0'
random_seed: 1234
batch_size: 4

evaluator:
  name: VolumeEvaluator
  eval_steps:  10
  metric_list:
    - 'Dice'
  save_image: true
  show_each_evaluate: true

estimator:
  allow_soft_placement: true
  gpu_options_allow_growth: true

dataset:
  name: 'CarcassDataset'
  modes: # 这里包含了具体几个模式的信息
    PREDICT:
      primary: true
      value: EvalMode3D
      dataset_path: 'eval_ThreeDExample.yaml'

  min_window_level: 0
  max_window_level: 5000
  image_height: 256
  image_width: 256
  num_parallel_batches: 1
  image_augmentation:

model:
  model_dir: '_model_dir'
  #  checkpoint: 'checkpoint_best'
  networks:
    UNet:
      is_training: true
      init_channels: 64
      classes:
        background:
          show: false
          weight: 0.5
        carcass:
          show: true
          weight: 2
      loss:
        name: 'weighted_sparse_softmax_cross_entropy'
      train_metrics:
        dice:
          eps: 1e-5
      num_down_samples: 5

  solver:
    slow_start_step: 0
    slow_start_learning_rate: 1e-4
    learning_rate:
      name: 'piecewise_constant'
      boundaries:
        - 100000
        - 150000 # learning_rate_decay_boundaries
      values:
        - 0.003
        - 0.0003
        - 0.0001 # learning_rate_custom_values
    optimizer:
      name: 'adam'
      beta1: 0.9 # 参数什么意思
      beta2: 0.99

hooks:
# 默认含有的hooks
# util._DatasetInitializerHook
# StopAtStepHook
# NanTensorHook
# LoggingTensorHook
# IteratorStringHandleHook:
# LogLearningRateHook:




