tag: 'carcass_3d_unet' # 这次训练的名称
CUDA_VISIBLE_DEVICES: '1'
random_seed: 1234
batch_size: 4

evaluator:
  name: VolumeEvaluator
  eval_steps:  10
  metric_list:
    - 'Dice'
  save_image: true
  show_each_evaluate: true

dataset:
  name: 'CarcassDataset'
  modes: # 这里包含了具体几个模式的信息
    PREDICT:
      primary: true
      value: EvalMode3D
      dataset_path: 'eval_ThreeDExample.yaml'

  image_height: 512
  image_width: 128
  min_window_level: 0
  max_window_level: 2000
  num_parallel_batches: 1
  image_augmentation:

estimator:
  allow_soft_placement: true
  gpu_options_allow_growth: true

model:
  model_dir: '_model_dir'
  networks:
    UNet:
      is_training: false
      init_channels: 64
      classes:
        background:
          show: false
          weight: 0.2
        body:
          show: true
          weight: 0.1
      loss_name: 'weighted_sparse_softmax_cross_entropy'
      train_metrics:
        dice:
          eps: 1e-5
      num_down_samples: 4




