random_seed: 1234

dataset:
  name: 'BodyDataset'

  source_data:
    path: 'E:/Slimed_NF' #'/home/yf/Slimed_NF'
    reader_tools: 'ImageReader'
    extra:
      image_pattern: 'STIR.mhd' # 用来过滤文件，获取正确文件的
      label_pattern: 'STIR_Label.mhd'

  output_data:
    data_record: 'records' # tfrecord数据存放位置
    k: 5 # 分成k份文件
    train_scale: 0.8
    image_channel: 3

  examples:
    value:
      - 'TwoDExample'
      - 'ThreeDExample'

  extra:
    value: None





