random_seed: 1234

dataset:
  name: 'CarcassDataset'

  source_data:
    path: 'E:/Corpus_Callosum' #''
    extra:

  output_data:
    data_record: 'records' # tfrecord数据存放位置
    k: 5 # 分成k份文件
    train_scale: 0.8

  examples:
    value:
      - 'TwoDExample'

  extra:
    value: None





